# Copyright AI-Catalog Contributors (https://github.com/Agent-Card/ai-catalog-rust)
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "1.95.0"
profile = "minimal"
components = ["clippy", "rustfmt"]
