# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-rust

on:
  push:
    branches:
      - main

jobs:
  release-crates:
    name: Release catalog crates
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run release-plz
        uses: release-plz/action@1528104d2ca23787631a1c1f022abb64b34c1e11 # v0.5.128
        with:
          command: release
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml

  release-crates-pr:
    name: Release catalog crates - PR
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Run release-plz - PR
        uses: release-plz/action@1528104d2ca23787631a1c1f022abb64b34c1e11 # v0.5.128
        with:
          command: release-pr
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml
